kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 2
cpu: 200m
memory: 400Mi
db_tier: db-f1-micro
db_highAvailability: false
db_pointInTimeRecovery: false
flex-openapi-docs-ui: true
env:
  SPRING_PROFILES_ACTIVE: default,testdatareset
  DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
  AIVEN_KAFKA_AUTO_OFFSET_RESET: latest
