azureTenant: trygdeetaten.no
kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 2
cpu: 400m
memory: 768Mi
db_tier: db-f1-micro
db_highAvailability: false
db_pointInTimeRecovery: false
external-host:
  - pdl-api.dev-fss-pub.nais.io
  - aareg-services-q2.dev-fss-pub.nais.io
  - ereg-services-q2.dev-fss-pub.nais.io
flex-openapi-docs-ui: true
env:
  SPRING_PROFILES_ACTIVE: default,testdata
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
  SYKEPENGESOKNAD_CLIENT_ID: dev-gcp:flex:sykepengesoknad
  AIVEN_KAFKA_AUTO_OFFSET_RESET: latest
  AAREG_HENDELSE_TOPIC: arbeidsforhold.aapen-aareg-q1-arbeidsforholdhendelse-v1
  EREG_URL: https://ereg-services-q2.dev-fss-pub.nais.io
  AAREG_URL: https://aareg-services-q2.dev-fss-pub.nais.io
  AAREG_AAD_CLIENT_ID: dev-fss.arbeidsforhold.aareg-services-nais-q2
  FLEX_SYKETILFELLE_URL: http://flex-syketilfelle
  FLEX_SYKETILFELLE_TOKENX_CLIENT_ID: dev-gcp:flex:flex-syketilfelle