apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-sykmeldinger-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
    {{#each external-host}}
        - host: {{this}}
    {{/each}}
    inbound:
      rules:
        - application: ditt-sykefravaer
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        diskType: SSD
        diskSize: 10
        tier: {{db_tier}}
        highAvailability: {{db_highAvailability}}
        pointInTimeRecovery: {{db_pointInTimeRecovery}}
        diskAutoresize: true
        databases:
          - name: flex-sykmeldinger-backend-db
            users:
              - name: bigquery-datastream
            envVarPrefix: DATABASE
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  azure:
    application:
      enabled: true
      allowAllUsers: false
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
