azureTenant: nav.no
kafkaPool: nav-prod
environment: prod
replicas_min: 2
replicas_max: 3
cpu: 500m
memory: 1000Mi
db_tier: db-custom-4-15360
db_highAvailability: true
external-host:
  - pdl-api.prod-fss-pub.nais.io
  - aareg-services.prod-fss-pub.nais.io
  - ereg-services.prod-fss-pub.nais.io
db_pointInTimeRecovery: true
env:
  SPRING_PROFILES_ACTIVE: default
  PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
  DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID: prod-gcp:flex:ditt-sykefravaer
  AAREG_HENDELSE_TOPIC: arbeidsforhold.aapen-aareg-arbeidsforholdhendelse-v1
  REGISTRERT_FOR_ARBEIDSFORHOLD: false
  EREG_URL: https://ereg-services.prod-fss-pub.nais.io
  AAREG_URL: https://aareg-services.prod-fss-pub.nais.io
  AAREG_AAD_CLIENT_ID: prod-fss.arbeidsforhold.aareg-services-nais
  FLEX_SYKETILFELLE_URL: http://flex-syketilfelle
  FLEX_SYKETILFELLE_TOKENX_CLIENT_ID: prod-gcp:flex:flex-syketilfelle
