package no.nav.helse.flex.api.dto

data class RegelinfoDTO(
    val messageForSender: String,
    val messageForUser: String,
    val ruleName: String,
    val ruleStatus: RegelStatusDTO?,
)

enum class RuleNameDTO {
    BEHANDLER_IKKE_GYLDIG_I_HPR,
    BEHANDLER_MANGLER_AUTORISASJON_I_HPR,
    BEHANDLER_IKKE_LE_KI_MT_TL_FT_I_HPR,
    BEHANDLER_MT_FT_KI_OVER_12_UKER,
    BEHANDLER_SUSPENDERT,
    PASIENT_ELDRE_ENN_70,
    ICPC_2_Z_DIAGNOSE,
    GRADERT_UNDER_20_PROSENT,
    INNTIL_30_DAGER,
    OPPHOLD_MELLOM_PERIODER,
    TOTAL_VARIGHET_OVER_ETT_AAR,
    FREMDATERT,
    TILBAKEDATERT_FORLENGELSE_OVER_1_MND,
    TILBAKEDATERT_MER_ENN_8_DAGER_FORSTE_SYKMELDING,
    UGYLDIG_KODEVERK_FOR_HOVEDDIAGNOSE,
    GRADERT_SYKMELDING_UNDER_20_PROSENT,
    TILBAKEDATERING_UGYLDIG_TILBAKEDATERING,
    INNTIL_8_DAGER,
    GRADERT_SYKMELDING_OVER_99_PROSENT,
    MINDRE_ENN_1_MAANED,
    OVER_1_MND,
    UGYLDIG_KODEVERK_FOR_BIDIAGNOSE,
    TILBAKEDATERT_FORLENGELSE_UNDER_1_MND,
    INNTIL_1_MAANDE,
    OVER_30_DAGER,
    FOR_MANGE_BEHANDLINGSDAGER_PER_UKE,
    TILBAKEDATERT_INNTIL_8_DAGER_UTEN_KONTAKTDATO_OG_BEGRUNNELSE,
    TILBAKEDATERT_MER_ENN_3_AR,
    IKKE_DEFINERT_PERIODE,
    OVERLAPPENDE_PERIODER,
    UGYLDIG_FNR_BEHANDLER,
    BEHANDLINGSDATO_ETTER_MOTTATTDATO,
    MANGLENDE_DYNAMISKE_SPOERSMAL_VERSJON2_UKE_39,
    TILBAKEDATERT_MANGLER_BEGRUNNELSE,
    ;

    companion object {
        val NAVN_SET: Set<String> = entries.map { it.name }.toSet()
    }
}
