ALTER TABLE SYKMELDING
    RENAME COLUMN OPPDATERT TO HENDELSE_OPPDATERT
;
ALTER TABLE SYKMELDING
    ADD COLUMN SYKMELDING_GRUNNLAG_OPPDATERT TIMESTAMP WITH TIME ZONE NULL,
    ADD COLUMN VALIDATION_OPPDATERT TIMESTAMP WITH TIME ZONE NULL
;
