CREATE TABLE SYKMELDINGHENDELSE_BUFFER
(
    ID                              VARCHAR(36) DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    SYKMELDING_ID                   VARCHAR(36)              NOT NULL,
    SYKMELDING_STATUS_OPPRETTET     TIMESTAMP WITH TIME ZONE NOT NULL,
    SYKMELDING_STATUS_KAFKA_MESSAGE JSONB                    NOT NULL,
    LOKALT_OPPRETTET                TIMESTAMP WITH TIME ZONE NOT NULL
);