CREATE TABLE TEMP_TSM_SYKMELDINGSTATUS
(
    TIMESTAMP     TIMESTAMP WITH TIME ZONE NOT NULL,
    SYKMELDING_ID TEXT                     NOT NULL,
    EVENT         TEXT                     NOT NULL,
);