DROP TABLE IF EXISTS TEMP_TSM_HISTORISK_SYKMELDINGSTATUS;

CREATE TABLE TEMP_TSM_HISTORISK_SYKMELDINGSTATUS
(
    SYKMELDING_ID          TEXT                     NOT NULL,
    TIMESTAMP              TIMESTAMP WITH TIME ZONE NOT NULL,
    EVENT                  TEXT                     NOT NULL,
    ARBEIDSGIVER           JSONB NULL,
    SPORSMAL               JSONB NULL,
    TIDLIGERE_ARBEIDSGIVER JSONB NULL,
    ALLE_SPROSMAL          JSONB NULL,
);