CREATE INDEX TEMP_TSM_HISTORISK_SYKMELDINGSTATUS_SYKMELDING_ID_IDX ON TEMP_TSM_HISTORISK_SYKMELDINGSTATUS (sykmelding_id);

ALTER TABLE TEMP_TSM_HISTORISK_SYKMELDINGSTATUS
    ADD COLUMN lest_inn BOOLEAN NOT NULL DEFAULT FALSE;