CREATE INDEX IF NOT EXISTS TEMP_TSM_HISTORISK_SYKMELDINGSTATUS_SYKMELDING_ID_IDX ON TEMP_TSM_HISTORISK_SYKMELDINGSTATUS (sykmelding_id);

CREATE TABLE IF NOT EXISTS TEMP_TSM_HISTORISK_SYKMELDINGSTATUS_INNLESING
(
    sykmelding_id  TEXT PRIMARY KEY,
    lest_tidspunkt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
