CREATE INDEX IF NOT EXISTS SYKMELDING_OPPDATERT_IDX ON SYKMELDING (HENDELSE_OPPDATERT);
-- Omdøper ettersom lagd manuelt i prod
ALTER INDEX SYKMELDING_OPPDATERT_IDX RENAME TO SYKMELDING_HENDELSE_OPPDATERT_IDX;
CREATE INDEX IF NOT EXISTS SYKMELDING_OPPRETTET_IDX ON SYKMELDING (OPPRETTET);
CREATE INDEX IF NOT EXISTS SYKMELDINGHENDELSE_OPPRETTET_IDX ON SYKMELDINGHENDELSE (HENDELSE_OPPRETTET);
CREATE INDEX IF NOT EXISTS SYKMELDINGHENDELSE_LOKALT_OPPRETTET_IDX ON SYKMELDINGHENDELSE (LOKALT_OPPRETTET);